/*
Created: 11/13/2020
Modified: 11/13/2020
Model: My SQL8
Database: MySQL 8.0
*/

-- Create tables section -------------------------------------------------

-- Table PROJECT

CREATE TABLE PROJECT
(
  PROJECT_ID Int NOT NULL AUTO_INCREMENT,
  DESCR Varchar(100) NOT NULL,
  WORKFLOW_ID Int NOT NULL,
  STEP_ID Int NOT NULL,
  UPDATE_DT Datetime NOT NULL,
  OWNER_ID Int,
  UPDATE_USERID Int,
  PRIMARY KEY (PROJECT_ID)
)
;

CREATE INDEX IX_Relationship9 ON PROJECT (OWNER_ID)
;

CREATE INDEX IX_Relationship10 ON PROJECT (UPDATE_USERID)
;

CREATE INDEX IX_Relationship12 ON PROJECT (WORKFLOW_ID)
;

CREATE INDEX IX_Relationship13 ON PROJECT (STEP_ID)
;

-- Table RD_OBJECT

CREATE TABLE RD_OBJECT
(
  OBJECTID Int NOT NULL AUTO_INCREMENT,
  OBJECT_TYPE_ID Int,
  DESCR Varchar(300),
  PRIMARY KEY (OBJECTID)
)
;

-- Table PROJECT_OBJECT

CREATE TABLE PROJECT_OBJECT
(
  PROJECT_ID Int NOT NULL,
  OBJECTID Int NOT NULL
)
;

ALTER TABLE PROJECT_OBJECT ADD PRIMARY KEY (PROJECT_ID, OBJECTID)
;

-- Table PROJECT_ARCHIVE

CREATE TABLE PROJECT_ARCHIVE
(
  ARCHIVE_ID Int NOT NULL AUTO_INCREMENT,
  PROJECT_ID Int NOT NULL,
  ENV_ID Int,
  PRIMARY KEY (ARCHIVE_ID)
)
;

CREATE INDEX IX_Relationship5 ON PROJECT_ARCHIVE (PROJECT_ID)
;

CREATE INDEX IX_Relationship8 ON PROJECT_ARCHIVE (ENV_ID)
;

-- Table PROJECT_ARCHIVE_OBJECT

CREATE TABLE PROJECT_ARCHIVE_OBJECT
(
  ARCHIVE_ID Int NOT NULL,
  OBJECTID Int NOT NULL
)
;

ALTER TABLE PROJECT_ARCHIVE_OBJECT ADD PRIMARY KEY (ARCHIVE_ID, OBJECTID)
;

-- Table RD_ENVIRONMENT

CREATE TABLE RD_ENVIRONMENT
(
  ENV_ID Int NOT NULL AUTO_INCREMENT,
  DESCR Varchar(50) NOT NULL,
  STATUS_CD Char(1) NOT NULL,
  PRIMARY KEY (ENV_ID)
)
;

-- Table RD_USER

CREATE TABLE RD_USER
(
  USER_ID Int NOT NULL AUTO_INCREMENT,
  LAST_NAME Varchar(30) NOT NULL,
  FIRST_NAME Varchar(30) NOT NULL,
  STATUS_CD Char(1) NOT NULL,
  PRIMARY KEY (USER_ID)
)
;

-- Table RD_WORKFLOW

CREATE TABLE RD_WORKFLOW
(
  WORKFLOW_ID Int NOT NULL AUTO_INCREMENT,
  DESCR Varchar(30) NOT NULL,
  STATUS_CD Char(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (WORKFLOW_ID)
)
;

-- Table RD_STEP

CREATE TABLE RD_STEP
(
  STEP_ID Int NOT NULL AUTO_INCREMENT,
  DESCR Varchar(50) NOT NULL,
  STATUS_CD Char(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (STEP_ID)
)
;

-- Create foreign keys (relationships) section -------------------------------------------------

ALTER TABLE PROJECT_OBJECT ADD CONSTRAINT Relationship1 FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE PROJECT_OBJECT ADD CONSTRAINT Relationship2 FOREIGN KEY (OBJECTID) REFERENCES RD_OBJECT (OBJECTID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE PROJECT_ARCHIVE ADD CONSTRAINT PROJECT_FK1 FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE PROJECT_ARCHIVE_OBJECT ADD CONSTRAINT PROJECT_ARCHIVE_FK1 FOREIGN KEY (ARCHIVE_ID) REFERENCES PROJECT_ARCHIVE (ARCHIVE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE PROJECT_ARCHIVE_OBJECT ADD CONSTRAINT RD_OBJECT_FK1 FOREIGN KEY (OBJECTID) REFERENCES RD_OBJECT (OBJECTID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE PROJECT_ARCHIVE ADD CONSTRAINT RD_ENVIRONMENT_FK1 FOREIGN KEY (ENV_ID) REFERENCES RD_ENVIRONMENT (ENV_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE PROJECT ADD CONSTRAINT RD_USER_FK1 FOREIGN KEY (OWNER_ID) REFERENCES RD_USER (USER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE PROJECT ADD CONSTRAINT RD_USER_FK2 FOREIGN KEY (UPDATE_USERID) REFERENCES RD_USER (USER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE PROJECT ADD CONSTRAINT RD_WORKFLOW_FK1 FOREIGN KEY (WORKFLOW_ID) REFERENCES RD_WORKFLOW (WORKFLOW_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE PROJECT ADD CONSTRAINT RD_STEP_FK1 FOREIGN KEY (STEP_ID) REFERENCES RD_STEP (STEP_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

